# typed: false
# frozen_string_literal: true

# Generated by packages/cli/scripts/update-formula.mjs - do not edit by hand.
class Macrohill < Formula
  desc "Run hardware-emulation test configs from the terminal"
  homepage "https://macrohill.com"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/pUrGe12/prod/releases/download/v0.1.0/macrohill-macos-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/pUrGe12/prod/releases/download/v0.1.0/macrohill-macos-x64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pUrGe12/prod/releases/download/v0.1.0/macrohill-linux-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/pUrGe12/prod/releases/download/v0.1.0/macrohill-linux-x64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install Dir["macrohill-*"].first => "macrohill"
  end

  test do
    assert_match "Macrohill CLI", shell_output("#{bin}/macrohill --help")
    assert_match version.to_s, shell_output("#{bin}/macrohill --version")
  end
end
