# typed: false
# frozen_string_literal: true

# Generated by packages/cli/scripts/update-formula.mjs - do not edit by hand.
class Macrohill < Formula
  desc "Run hardware-emulation test configs from the terminal"
  homepage "https://macrohill.com"
  version "0.2.0"

  on_macos do
    on_arm do
      url "https://github.com/pUrGe12/homebrew-tap/releases/download/v0.2.0/macrohill-macos-arm64"
      sha256 "db2f857cd951d8e8671e4f93cce439656b37188ccfbc22278c1d5babf07165a3"
    end
    on_intel do
      url "https://github.com/pUrGe12/homebrew-tap/releases/download/v0.2.0/macrohill-macos-x64"
      sha256 "7dcc2d463c956810de2e6ca07e339b94a87114cf191255b6bbf4dea65db2f455"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pUrGe12/homebrew-tap/releases/download/v0.2.0/macrohill-linux-arm64"
      sha256 "4696b8652b30539f88333fb571fa9b67318336c72c38db2e9c4df8f28ef236e5"
    end
    on_intel do
      url "https://github.com/pUrGe12/homebrew-tap/releases/download/v0.2.0/macrohill-linux-x64"
      sha256 "865af2867187fc7b7d1ae483966fa138da85b1cde170081648d9bc23fe60d817"
    end
  end

  def install
    bin.install Dir["macrohill-*"].first => "macrohill"
  end

  test do
    assert_match "Macrohill CLI", shell_output("#{bin}/macrohill --help")
    assert_match version.to_s, shell_output("#{bin}/macrohill --version")
  end
end
